### PR TITLE
GenEd25519KeyPair* helpers added

### PR DESCRIPTION
**Pull request by odeke-em**
Fixes https://github.com/tendermint/go-crypto/issues/31

Add a helper to be able to generate Ed25519 keys directly
from our crypto package, and with these helpers we give
more context to a previously undocumented and hanging
code statement in which while generating a private key
we invoked ed25519.MakePublicKey, which is correct but
seemed hanging. With this change, the helpers are:
```go
func GenEd25519KeyPair() (priv PrivKeyEd25519, pub PubKeyEd25519)
func GenEd25519KeyPairFromSecret(secret []byte) (priv PrivKeyEd25519, pub PubKeyEd25519)
```

which are invoked by:
- GenPrivKeyEd25519()
- GenPrivKeyEd25519FromSecret(secret []byte)
respectively and now with the pairings give more comfort knowing that
each private key for completion must be generated with its public key,
but we'll chose to discard the public key.

### CODE REVIEW

**Comment by ethanfrey** [comment]
Huh?  I was used to generating a private key, and later always just called privKey.PubKey() when I needed it.

The code looks correct, still not sure it makes life easier. Can you reference another package that uses this library that would be improved by this change?

**Comment by ebuchman** [comment]
Hmm I agree with Frey here. Why do this when we can just `privKey.PubKey()` ?

**Comment by odeke-em** [comment]
Thanks for the input @ethanfrey @ebuchman, sorry for the late reply, been off for a bit.
So unfortunately that wasn't documented(at least I did not find it easily).

**Comment by odeke-em** [comment]
@ethanfrey in regards to packages that would need this, I needed this for this PR https://github.com/tendermint/tendermint/pull/648/files#diff-4b45e760192d8a11e9b4e278a8c8ea32R115

**Comment by ebuchman** [comment]
Is the following not sufficient:

```
pubKey := crypto.GenPrivKeyEd25519().PubKey()
```
?

**Comment by odeke-em** [comment]
@ebuchman it is sufficient indeed, but now that y'all pointed me to it. That didn't seem documented, at least I couldn't easily find a reference to it.

**Comment by ebuchman** [comment]
So let's close this an open an issue to create a doc.go explaining how this package works?

**Comment by odeke-em** [comment]
SGTM, great idea!

**Comment by odeke-em** [comment]
Thanks @ebuchman and @ethanfrey for the review and the direction, I've opened https://github.com/tendermint/go-crypto/issues/35 which supersedes this PR.

**Pull request closed without merging**
