### PR TITLE
SignatureKey -> Signature

### PR DESCRIPTION
**Pull request by ebuchman**
Ref https://github.com/tendermint/go-crypto/issues/84

@Liamsi can you add https://github.com/tendermint/go-crypto/issues/88 so we can get the updated info for the docs: https://github.com/tendermint/tendermint/blob/master/docs/spec/blockchain/encoding.md#pubkeyed25519

We can probably simplify those docs a bunch by just using a table instead of all the verbosity I have there now ...

### CODE REVIEW

**Comment by liamsi** [comment]
Yes, will add something that prints a table in markdown. This can be copy & pasted to update the documentation. Be aware that this also requires changes in amino though. (everything related to the type info is currently not exported). 
Also, you only need the concrete types (not the interfaces), I assume?

**Comment by liamsi** [comment]
How does this look to you:

| Type | Name | Prefix | Length | Notes |
| ---- | ---- | ------ | ----- | ------ |
| PubKeyEd25519 | tendermint/PubKeyEd25519 | 0x1624DE62 | 0x20 |  |
| PubKeyLedgerEd25519 | tendermint/PubKeyLedgerEd25519 | 0x5C3453B2 | 0x20 |  |
| PubKeySecp256k1 | tendermint/PubKeySecp256k1 | 0xEB5AE982 | 0x21 |  |
| PrivKeyEd25519 | tendermint/PrivKeyEd25519 | 0xA3288912 | 0x40 |  |
| PrivKeySecp256k1 | tendermint/PrivKeySecp256k1 | 0xE1B0F79A | 0x20 |  |
| PrivKeyLedgerSecp256k1 | tendermint/PrivKeyLedgerSecp256k1 | 0x10CAB393 | variable |  |
| PrivKeyLedgerEd25519 | tendermint/PrivKeyLedgerEd25519 | 0x0CFEEF9B | variable |  |
| SignatureEd25519 | tendermint/SignatureKeyEd25519 | 0x3DA1DB2A | 0x40 |  |
| SignatureSecp256k1 | tendermint/SignatureKeySecp256k1 | 0x16E1FEEA | variable |  |

**Comment by liamsi** [comment]
updated the docs here: https://github.com/Liamsi/tendermint-1/blob/978277a4c18258a8aaa1a829c4924a31e96d9270/docs/spec/blockchain/encoding.md

I'm wondering if we even need the "Notes" column?

/cc @ebuchman

**Comment by ebuchman** [comment]
> I'm wondering if we even need the "Notes" column?

Seems not, at least for now

**Comment by liamsi** [comment]
> Seems not, at least for now

OK, (manually) removed it in https://github.com/tendermint/tendermint/pull/1662

**Comment by xla** [comment]
@Liamsi Let's fix for `0.8.0`.

**Comment by liamsi** [comment]
PTAL @xla

**Review by xla — APPROVED** [review]
:+1: :octocat: :shipit: :dango:

**Pull request merged**
